---
environment_variables:
  SUNET_DOCKER_HOSTER_VERSION: "v1"
git:
  branch: develop
triggers:
  cron: "@daily"
clean_workspace: true
script:
  - echo "Build SUNET Docker-Hoster Image"
builders:
  - docker
docker_name: sunet/docker-hoster
